version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: mongo-rs
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db         # Host folder ./data stores DB files
      - ./init-replica.js:/docker-entrypoint-initdb.d/init-replica.js # Runs on first startup
    command: ["--replSet", "rs0"]
    restart: unless-stopped

volumes:
  data:
